### PR TITLE
Update readme.md to reflect npm scripts that were previously removed

### PR DESCRIPTION
**Pull request by jeremy-moffitt**
The README.md was never updated after https://github.com/crowbar/crowbar-ui/commit/a34c8478a1be05616b6f4d17384bb974ea59486d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
  which removed the preinstall and postinstall scripts from package.json

Update with the equivalent instructions here

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
It doesnt make any sense that changes to the Readme would fail CI... the error looks unrelated

**Comment by skazi0** [comment]
TravisCI failure is not related to your change. It should be fixed with: https://github.com/crowbar/crowbar-ui/pull/174

BTW, maybe you can mention `.travis.yml` as a source of hints on how to setup the test env and run tests?

BTW2, the mocked backend (i.e. `app.js` or `npm start`) is not feature complete. It was used in early development phases when we didn't have real backend yet. At the end it became too complicated to simulate different scenarios with this backend and we switched to testing with real cloud (mkcloud based).

**Comment by jeremy-moffitt** [comment]
let me know if any additional changes are needed, if nothing else its much more correct than before (it will start the UI running, though as you say its a poor substitute for a real environment). Looks like the change to fix the tests has a couple of approvals but hasnt merged yet....

**Comment by skazi0** [comment]
tests fix was merged. please rebase.

**Comment by jeremy-moffitt** [comment]
rebased and tests passing (thanks for fixing those!)

**Review by skazi0 — APPROVED** [review]

**Review by Itxaka — APPROVED** [review]

**Pull request merged**
