### PR TITLE
upgrade: Updated URL for node repo checks

### PR DESCRIPTION
**Pull request by skazi0**

### CODE REVIEW

**Comment by skazi0** [comment]
[(2) S50P14 #21 Add-On Product Repo Checks: Service Integration](https://trello.com/c/lqn8yLQ0/122-2-s50p14-21-add-on-product-repo-checks-service-integration)

**Review by Itxaka — APPROVED** [review]
Related commit: https://github.com/crowbar/crowbar-core/commit/f368845313fb0ecb14c7b8bd285d45bbcefb13fd

**Comment by santiph** [comment]
Is the new/renamed API endpoint available already to be tested?

**Comment by skazi0** [comment]
Yes. This PR is supposed to sync UI with current implementation in the backend.

**Pull request merged**
