### PR TITLE
upgrade: more coverage for upgrade-status.factory.js

### PR DESCRIPTION
**Pull request by Itxaka**
Tests the actual calls to the functions instead of testing for the timeout to have been called. Uses $timeout.flush() so indirectly is testing that the timeout works.

### CODE REVIEW

**Review by skazi0 — CHANGES_REQUESTED** [review]
I don't like this change at all... testing for `$timeout` call should be enough assuming that we can rely on external modules being tested.

The coverage increase is marginal and you loose important piece of test here. You only see that `waitForStepToEnd()` was called but you don't see if it was called via `$timeout`. Try removing the `$timeout` from the service code, call `waitForStepToEnd()` directly and the test will still pass. Current version will not behave too good either (infinite loop probably) but it will at least not hide the problem.

**Comment by Itxaka** [comment]
@skazi0 maybe I can put a spy on $timeot and check if timeout was called as well?

**Comment by skazi0** [comment]
`$timeout` is a tricky beast. Doesn't like being spied on :)

**Comment by santiph** [comment]
As `$timeout` is an angular service and we can assume it works as expected.
We should test `$timeout` has been called as expected, but not its inner functionality nor assert the method is actually being called after the delay.

**Comment by Itxaka** [comment]
> I don't like this change at all... testing for $timeout call should be enough assuming that we can rely on external modules being tested.

> We should test $timeout has been called as expected, but not its inner functionality nor assert the method is actually being called after the delay.

Not agreed.

Changing this line https://github.com/crowbar/crowbar-ui/blob/master/assets/app/data/crowbar/services/upgrade-status.factory.js#L64 to nonsense will make the tests pass with flying colours. The actual tests are also hiding part of the code working properly which could lead to issues in the future.


But I dont want to mock and reproduce the whole $timeout function to be able to spy on it, so I will close it. we will still have code in there *not* tested, but seems that we can live with that.¯\\\_(ツ)\_\/¯

**Comment by skazi0** [comment]
I found a better way to solve this problem by changing the service itself. Turns out `$timeout` has an optional last parameter which can be used to pass arguments to the callback function. With this in place, testing becomes way easier.

New PR: https://github.com/crowbar/crowbar-ui/pull/103

**Pull request closed without merging**
