### PR TITLE
Migrated Wiki sources to main git repo.

### PR DESCRIPTION
**Pull request by skazi0**
The built-in GitHub wiki is moved to the base git repo for easier change management via PRs.

### CODE REVIEW

**Comment by santiph** [comment]
I'm concerned about the lack of reusable pieces on github's markup to simulate the sidebar functionality as we have on https://github.com/crowbar/crowbar-ui/wiki
@aspiers you've requested the Wiki to be migrated originally. What would you recommend to solve this?

**Comment by santiph** [comment]
Also, @skazi0 some images has been recently updated (like https://github.com/crowbar/crowbar-ui/blob/wiki-assets/upgrade67/crowbar-upgrade-button-states.pdf) Could you please update that? I don't have the rights to upload files to your branch for some reason.

**Comment by skazi0** [comment]
Synced the contents of whole wiki with this branch.

**Review by aspiers — COMMENTED** [review]
Does it really make sense to move these to `doc/wiki/`?  They are no longer part of the wiki, so why label them that why?

@santiph I don't think GitHub has any native support for sidebars outside its wiki UI, and there's [a long-standing similar complaint about the lack of TOC auto-generation](https://github.com/isaacs/github/issues/215).  However I did find a [comment in that issue](https://github.com/isaacs/github/issues/215#issuecomment-202686599) linking to [this userscript](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-table-of-contents), which looks like it might be exactly what you want :-)

**Comment by aspiers** [comment]
s/that why/that way/

**Comment by skazi0** [comment]
I guess you're right about the wiki thing. I'll move it to the `doc` folder.

**Comment by skazi0** [comment]
As for the sidebar, I looked for some kind of `include` option but that doesn't seem to be available either (see: https://github.com/github/markup/issues/172#issuecomment-33241601).

**Comment by aspiers** [comment]
Also, once this gets merged, we should ensure that there are redirects from the wiki to the new location.

**Review by rsalevsky — APPROVED** [review]

**Comment by Itxaka** [comment]
+1

**Comment by rsalevsky** [comment]
@santiph Can we merge this?

**Comment by skazi0** [comment]
we're waiting for green light from @kwwii

**Comment by kwwii** [comment]
I do not agree with this change. If the design was final I would have no problem with it but at the current time I am still editing the wiki and re-designing pages. The last step still has open questions and we are learning and changing other steps due to this. Until the re-design is finished please do not remove the wiki or make anything else the main source of information.

**Comment by skazi0** [comment]
[(2) S49P18 Upgrade UI: Move documentation wikipage into .md files within the repo](https://trello.com/c/siiqLJNM/148-2-s49p18-upgrade-ui-move-documentation-wikipage-into-md-files-within-the-repo)

**Comment by skazi0** [comment]
Maybe this: https://brendancleary.com/2013/03/08/including-a-github-wiki-in-a-repository-as-a-submodule/ is a better option? Someone with a lot of free time could test it :)

**Pull request closed without merging**
