### PR TITLE
upgrade: Improve errors display

### PR DESCRIPTION
**Pull request by skazi0**
Added proper formatting of different data types (arrays, strings, multiline strings).
Adjusted colors to better match the rest of app. Added (i) icon and color to help text.

This is a follow up for base from #117

### CODE REVIEW

**Comment by skazi0** [comment]
Some examples of new styling:
zrzut ekranu z 2017-02-08 15-00-48
zrzut ekranu z 2017-02-08 15-01-19
zrzut ekranu z 2017-02-08 15-04-16
zrzut ekranu z 2017-02-08 15-27-02

**Comment by skazi0** [comment]
[(3) S55P3 #UI: Error messages definitions](https://trello.com/c/Mpu84gVE/246-3-s55p3-ui-error-messages-definitions)

**Review by Itxaka — APPROVED** [review]
Fancy!

**Comment by jsuchome** [comment]
I'm not sure about that red text on (semi-)red background. What about bold red text instead? (I'm not sure if it is good suggestion or if it fits to the rest of app, I was just inspired by those red labels here in github ;-) )

**Comment by Itxaka** [comment]
Bold text is ugly and from a geocities page :P

**Comment by kwwii** [comment]
lgtm

**Comment by skazi0** [comment]
@jsuchome the red on red is the default bootstrap styling. Let's wait for @kwwii to comment.

**Pull request merged**
