### PR TITLE
Fixed common layout

### PR DESCRIPTION
**Pull request by skazi0**
Fixed common layout:
- full height steps sidebar
- bottom margin in details part

Based on Solution1 from: http://stackoverflow.com/questions/19695784/how-can-i-make-bootstrap-columns-all-the-same-height

**Note: the height of the whole box is not fixed so it's going to change depending on the contents of the details section which might or might not be in line with the expectations. TBD.**

### CODE REVIEW

**Comment by skazi0** [comment]
This is how it looks like in firefox:
zrzut ekranu z 2016-09-01 12-07-16

And this is on a narrow screen:
zrzut ekranu z 2016-09-01 12-08-10

**Comment by bisht-richa** [comment]
Looks good.

**Comment by rsalevsky** [comment]
Can you make first letter from the first commit capital?

**Comment by skazi0** [comment]
Updated commit message.

**Comment by santiph** [comment]
Approved

**Pull request merged**
