### PR TITLE
Switched to v1 API for admin server backup.

### PR DESCRIPTION
**Pull request by skazi0**
The v1 API is available on Cloud6 so use this one instead of new v2 API for backups.
Note: https://github.com/crowbar/crowbar-core/pull/722 needs to be merged and get to the installation media before this will work as expected.

### CODE REVIEW

**Comment by santiph** [comment]
Looks good to me.
Can we merge this or should we wait for https://github.com/crowbar/crowbar-core/pull/722 to be merged first?

**Comment by skazi0** [comment]
https://github.com/crowbar/crowbar-core/pull/722 was merged already but I tested it even before with manually patched cloud. Feel free to merge it.

**Comment by skazi0** [comment]
[(1) S49P13 #8 Backup Admin Server: Service Integration](https://trello.com/c/hw0n8t1G/129-1-s49p13-8-backup-admin-server-service-integration)

**Comment by Itxaka** [comment]
lgtm +1

**Pull request merged**
